services:
  client_test:
    image: cypress/included:8.7.0
    working_dir: /tests
    volumes:
      # USER passthrough
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # mount tests - readonly
      - ${PWD}/client_test/cypress.json:/tests/cypress.json:ro
      - ${PWD}/client_test/cypress:/tests/cypress:ro
      # mount reports - writeable
      - ${PWD}/client_test/reports:/tests/reports:rw
    entrypoint: ["cypress"]
    command: ["run"]
